"""Per-test tmp_path-isolated state.db fixture.

Eliminates Pattern #8 reinforcement #3 (test cleanup leak class — production
tables polluted by test runs from derivative IDs generated by production
code that the test's prefix-based cleanup() doesn't track). Banking
principle #7: enforce test isolation at the fixture level, not via cleanup
discipline.

Phase 2.5 promotion (banked 2026-05-09): MUST-DO before Wave 1 code starts
— every new test added under the cleanup-discipline pattern would extend
the leak surface.

Design (per SESSION_STARTER.md Day 1 directive 2026-05-13):
- Session-scoped template DB: `alembic upgrade head` runs once per test
  session against a tmp_path_factory location. Saves ~15-45s vs per-test
  migration on a 15-test suite.
- Function-scoped autouse `isolated_db`: copies the template, creates
  `_data/` artifact subdirs under tmp_path, monkey-patches db module
  globals + 5 dependent modules that snapshot `db.DATA_DIR` at import
  time as module-level constants (runtime, router_tail, retry_queue,
  thumbnails, watcher).
- Tests keep existing main()/cleanup() bookends. Each test file adds
  `def test_main(): assert main() == 0` for pytest discovery; the autouse
  fixture wraps it. Standalone `python tests/test_X.py` still works.

This conftest depends on the `TOOL_BUILD_ALEMBIC_URL` env var override
added to migrations/env.py 2026-05-13.
"""

from __future__ import annotations

import os
import shutil
import sqlite3
import sys
from pathlib import Path

import pytest

TOOL_BUILD_DIR = Path(__file__).resolve().parent.parent
if str(TOOL_BUILD_DIR) not in sys.path:
    sys.path.insert(0, str(TOOL_BUILD_DIR))


# _data/ artifact subdirs production code expects to find. Mirrors
# serve.py:ARTIFACT_SUBDIRS plus the Phase 2 audit tables and the
# Phase 2.5 thumbnails cache.
_ARTIFACT_SUBDIRS = (
    "concepts",
    "prompts",
    "renders",
    "generation_attempts",
    "verdicts",
    "hero_promotions",
    "lineage_edges",
    "cross_ai_captures",
    "tool_grammar_configs",
    "audit_sessions",
    "ai_consultations",
    "audit_thumbnails",
    "_audit_thumbnails",
    # Migration 0004 additions
    "notes_md_state",
    "audio_assets",
)


@pytest.fixture(scope="session")
def template_db(tmp_path_factory):
    """Build a schema-head template DB once per test session.

    Subsequent per-test fixtures copy this template instead of re-running
    Alembic migrations on every test.
    """
    template_dir = tmp_path_factory.mktemp("alembic_template")
    template_path = template_dir / "state.db"

    old_url = os.environ.get("TOOL_BUILD_ALEMBIC_URL")
    os.environ["TOOL_BUILD_ALEMBIC_URL"] = f"sqlite:///{template_path.as_posix()}"
    try:
        from alembic.config import Config
        from alembic import command

        cfg = Config(str(TOOL_BUILD_DIR / "alembic.ini"))
        command.upgrade(cfg, "head")
    finally:
        if old_url is None:
            os.environ.pop("TOOL_BUILD_ALEMBIC_URL", None)
        else:
            os.environ["TOOL_BUILD_ALEMBIC_URL"] = old_url

    return template_path


@pytest.fixture(autouse=True)
def isolated_db(tmp_path, template_db, monkeypatch):
    """Per-test tmp_path-isolated state.db + _data/ tree.

    Pattern #8 reinforcement #3 + Banking principle #7. Tests never touch
    production state.db; the entire class of cleanup-leak failures
    (derivative IDs generated by production code not tracked by test
    prefix-based cleanup) becomes structurally impossible.
    """
    # Mirror the canonical repo structure under tmp_path so that test code
    # which computes `abs_path.relative_to(repo_root)` works correctly.
    # Production code stores filepaths as repo-relative strings and resolves
    # them via db.REPO_ROOT/path; tests that create real files need both
    # write-path (db.DATA_DIR) AND resolve-root (db.REPO_ROOT) patched to a
    # consistent fake-repo location.
    fake_tool_build_dir = tmp_path / "projects" / "latent_systems" / "tool_build"
    fake_tool_build_dir.mkdir(parents=True)
    test_data_dir = fake_tool_build_dir / "_data"
    test_data_dir.mkdir()
    test_db_path = test_data_dir / "state.db"

    shutil.copy(template_db, test_db_path)

    for subdir in _ARTIFACT_SUBDIRS:
        (test_data_dir / subdir).mkdir(exist_ok=True)

    # Patch db module globals first — call sites using db.DB_PATH / db.DATA_DIR
    # / db.REPO_ROOT / db.TOOL_BUILD_DIR via attribute access (audit.py,
    # audit_consult.py, dispatcher.py, walker.py, thumbnails.py, etc.)
    # pick this up dynamically.
    import db
    monkeypatch.setattr(db, "TOOL_BUILD_DIR", fake_tool_build_dir)
    monkeypatch.setattr(db, "DB_PATH", test_db_path)
    monkeypatch.setattr(db, "DATA_DIR", test_data_dir)
    monkeypatch.setattr(db, "REPO_ROOT", tmp_path)

    # Patch the 5 dependent modules that snapshot db.DATA_DIR at import time
    # as module-level constants. These need explicit patches because the
    # snapshot is frozen at the value db.DATA_DIR held when the module was
    # first imported. monkeypatch.setattr's string form auto-imports.
    monkeypatch.setattr("runtime.DATA_DIR", test_data_dir)
    monkeypatch.setattr("router_tail.CURSOR_FILE",
                        test_data_dir / "_router_log_cursor.json")
    monkeypatch.setattr("retry_queue.QUEUE_FILE",
                        test_data_dir / "_retry_queue.yaml")
    monkeypatch.setattr("thumbnails.THUMBNAIL_DIR",
                        test_data_dir / "_audit_thumbnails")
    monkeypatch.setattr("watcher.PENDING_FILE",
                        test_data_dir / "_pending_downloads.json")

    # Seed tool-grammar configs to mirror what --init does in production.
    # test_retry_queue.draft_via_api and any future test that exercises
    # dispatcher.draft_via_api expects seeds/mj.yaml to be available at
    # _data/tool_grammar_configs/mj.yaml. Auto-iterating handles future
    # seeds (gpt.yaml, kling.yaml, etc.) per Phase 3 expansion.
    import seeds_loader
    seeds_dir = TOOL_BUILD_DIR / "seeds"
    if seeds_dir.exists():
        for seed_file in seeds_dir.glob("*.yaml"):
            seeds_loader.load_tool_grammar_seed(seed_file.stem)

    yield test_data_dir


@pytest.fixture
def production_state_db_row_counts():
    """Optional assertion fixture — proves Pattern #8 reinforcement #3 fix
    actually works by comparing production state.db row counts before/after.

    Used by the proof-of-concept validation step. Not autouse — only tests
    that explicitly take this fixture run the assertion.

    Yields the pre-test row-count dict; after yield, re-reads and asserts
    equality. Skips silently if no production state.db exists.
    """
    prod_db = TOOL_BUILD_DIR / "_data" / "state.db"
    if not prod_db.exists():
        yield None
        return

    before = _read_row_counts(prod_db)
    yield before
    after = _read_row_counts(prod_db)

    if before != after:
        diffs = {
            t: (before.get(t, 0), after.get(t, 0))
            for t in set(before) | set(after)
            if before.get(t, 0) != after.get(t, 0)
        }
        raise AssertionError(
            f"Production state.db row counts changed during test: {diffs}. "
            f"Fixture isolation is broken — production tables were touched."
        )


def _read_row_counts(db_path: Path) -> dict[str, int]:
    """Return {table_name: row_count} for all user tables in the DB."""
    conn = sqlite3.connect(db_path)
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        tables = [
            r[0] for r in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table' "
                "AND name NOT LIKE 'sqlite_%' AND name != 'alembic_version'"
            ).fetchall()
        ]
        return {t: conn.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
                for t in tables}
    finally:
        conn.close()
